# Railway deployment configuration for PDF generation service

[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
FLASK_ENV = "production"
COMPRESSION_ENABLED = "true"
COMPRESSION_LEVEL = "3"
MAX_FILE_AGE_HOURS = "24"
UPLOAD_FOLDER = "generated_pdfs"

[environments.staging.variables]
FLASK_ENV = "development"
FLASK_DEBUG = "true"
COMPRESSION_ENABLED = "true"
COMPRESSION_LEVEL = "2"
MAX_FILE_AGE_HOURS = "6"
UPLOAD_FOLDER = "generated_pdfs"
